[package]
name = "zbusctl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
zbus = { version = "5", features = ["tokio"] }
zvariant = "5"
